branch-defaults:
  development:
    environment: DevENV
environment-defaults:
  DevENV:
    branch: null
    repository: null
global:
  application_name: sinatra_pgsql_eb_test
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Puma with Ruby 2.3
    running on 64bit Amazon Linux/2.5.0
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
